In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv("pre_taxa_sim.csv", encoding='latin1')
df

,municipio,id_municipio,ano,faixa_etaria,pop_total,pop_pad_total,pop_homem,pop_pad_homem,pop_mulher,pop_pad_mulher,...,taxa_obitos_total,taxa_obitos_homem,taxa_obitos_mulher,obitos_esp_total,obitos_esp_homem,obitos_esp_mulher,taxa_obitos_esp_total,taxa_obitos_esp_homem,taxa_obitos_esp_mulher,grupo
0,AbaetÃ©,310020,2010,0a4,1377,1338553,702,684629,675,653924,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0
1,AbaetÃ©,310020,2010,0a4,1377,1338553,702,684629,675,653924,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0
2,AbaetÃ©,310020,2010,0a4,1377,1338553,702,684629,675,653924,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0
3,AbaetÃ©,310020,2010,0a4,1377,1338553,702,684629,675,653924,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0
4,AbaetÃ©,310020,2010,0a4,1377,1338553,702,684629,675,653924,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14687995,Vespasiano,317120,2019,>=80anos,1507,334532,528,129431,979,205101,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0
14687996,Vespasiano,317120,2019,>=80anos,1507,334532,528,129431,979,205101,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0
14687997,Vespasiano,317120,2019,>=80anos,1507,334532,528,129431,979,205101,...,862.641009,2462.121212,1327.885598,2885.810219,3186.748106,2723.506639,862.641009,2462.121212,1327.885598,3.0
14687998,Vespasiano,317120,2019,>=80anos,1507,334532,528,129431,979,205101,...,862.641009,2462.121212,1327.885598,2885.810219,3186.748106,2723.506639,862.641009,2462.121212,1327.885598,3.0
14687999,Vespasiano,317120,2019,>=80anos,1507,334532,528,129431,979,205101,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0

In [21]:
municipios = [310020, 310320, 310390, 310480, 310500, 310620, 310640, 310670,
       310700, 310740, 310810, 310900, 310960, 310990, 311250, 311420,
       311560, 311750, 311760, 311787, 311800, 311810, 311860, 311890,
       311910, 312060, 312090, 312320, 312410, 312470, 312570, 312600,
       312640, 312720, 312760, 312980, 313010, 313020, 313100, 313110,
       313190, 313220, 313370, 313380, 313460, 313540, 313570, 313665,
       313760, 313810, 313830, 313880, 313970, 314050, 314070, 314110,
       314230, 314240, 314250, 314350, 314360, 314015, 314480, 314520,
       314580, 314610, 314640, 314690, 314740, 314710, 314930, 314960,
       315040, 315140, 315200, 315320, 315360, 315370, 315390, 315460,
       315480, 315530, 315670, 315720, 315780, 315850, 315900, 316040,
       316060, 316553, 316660, 316720, 316170, 316180, 316210, 316292,
       316295, 316310, 316890, 317120]

In [29]:
pop_pad_t = df['pop_pad_total'].unique().sum()
pop_pad_h = df['pop_pad_homem'].unique().sum()
pop_pad_m = df['pop_pad_mulher'].unique().sum()

In [30]:
df_r = df[df['ano'] != 2019]
pop_r = df_r.groupby(['municipio', 'id_municipio', 'agravo'], as_index=False).sum()

pop_r['pop_total'] = pop_r['pop_total'] / 12
pop_r['pop_homem'] = pop_r['pop_homem'] / 12
pop_r['pop_mulher'] = pop_r['pop_mulher'] / 12

pop_r['taxa_obitos_total'] = (pop_r['obitos_total'] / pop_r['pop_total']) * 100000
pop_r['taxa_obitos_homem'] = (pop_r['obitos_homem'] / pop_r['pop_homem']) * 100000
pop_r['taxa_obitos_mulher'] = (pop_r['obitos_mulher'] / pop_r['pop_mulher']) * 100000

pop_r['taxa_obitos_esp_total'] = (pop_r['obitos_esp_total'] / (pop_pad_t * 9)) * 100000
pop_r['taxa_obitos_esp_homem'] = (pop_r['obitos_esp_homem'] / (pop_pad_h * 9)) * 100000
pop_r['taxa_obitos_esp_mulher'] = (pop_r['obitos_esp_mulher'] / (pop_pad_m * 9)) * 100000

In [31]:
df_pre_media = pop_r[['agravo', 'taxa_obitos_esp_total']].groupby(['agravo'], as_index=False).mean()
df_pre_dp = pop_r[['agravo', 'taxa_obitos_esp_total']].groupby(['agravo'], as_index=False).std()

aux_pre = df_pre_media.merge(df_pre_dp, on=['agravo'])
aux_pre.columns = ['agravo', 'media_pre', 'dp_pre']
aux_pre

            agravo   media_pre     dp_pre
0         acidente   22.860254   8.962684
1         amebiase    0.037317   0.170397
2        ancilosto    0.000000   0.000000
3      ascaridiase    0.000030   0.000302
4             asma    1.302378   1.543214
5         broncoeq    0.101753   0.347289
6        bronquite   22.093920   6.957006
7           chagas    6.623623   6.819683
8     cisticercose    0.077928   0.274258
9           colera    0.000000   0.000000
10    conjuntivinv    0.000000   0.000000
11    conjuntivite    0.000000   0.000000
12          dengue    0.390983   0.617778
13         dermato    0.000000   0.000000
14         dhipert   21.550982   8.075988
15       diabetesm   21.973159   8.330836
16        diarreia    1.401416   1.344149
17           doecv   41.799200   9.592737
18     doencviaaer   23.498051   7.016487
19      doenisquem   34.478972  11.578759
20        doenpele    1.857108   1.359238
21     enterobiose    0.000000   0.000000
22        equinoco    0.000000   0.000000
23        esquisto    0.165746   0.343022
24      estrongilo    0.002188   0.020655
25        externas   70.893168  18.065599
26       extintind    9.916174   9.801013
27     extmorbmort    0.199504   0.519552
28       exttrauma   12.683738   4.690958
29    febreamarela    0.116873   0.429067
30      febreenter    0.000000   0.000000
31       filariose    0.001452   0.010700
32       hepatitea    0.027559   0.267328
33     hipertensao   11.858935   6.013266
34       homicidio   17.278804  12.309747
35        iamrecor   29.099513  10.478628
36    infecespperi    1.568853   1.792668
37       infecpele    0.519300   0.661661
38     infecvirais    0.048671   0.164151
39      insufrenal    4.560450   3.111398
40     intoxicacao    0.000000   0.000000
41        leishteg    0.014335   0.108485
42       leishvisc    0.136527   0.268180
43           lepto    0.025499   0.110936
44         malaria    0.004942   0.032091
45          micose    0.000000   0.000000
46        naturais  483.318152  55.487618
47            odip    0.158493   0.322234
48   outradoenresp    0.357918   1.943301
49      outraleish    0.004818   0.025659
50     outrasdavai    0.301697   0.977118
51     outrasiibac    0.068223   0.235839
52      outraspele    1.204033   0.992337
53        pneumoco    0.741853   2.539261
54    protozoarios    0.003585   0.035848
55       salmonela    0.000176   0.001761
56      shiguelose    0.000521   0.005209
57        suicidio    7.222508   5.282423
58       tbgenurin    0.012016   0.120160
59     tbintestino    0.010937   0.105331
60        tbmiliar    0.018579   0.057697
61         tbossea    0.000944   0.009066
62      tbsistnerv    0.018787   0.095059
63         teniase    0.000000   0.000000
64      tmusopsico    6.648656   3.683793
65           total  554.211320  62.025710
66         tracoma    0.000000   0.000000
67  transtafetivos    0.226600   0.421776
68     transtneuro    0.020639   0.094518
69      tricuriose    0.000000   0.000000
70         tubresp    0.872673   1.155694
71          veneno    0.165104   0.461781

In [32]:
df_19 = df[df['ano'] == 2019]
pop_19 = df_19.groupby(['municipio', 'id_municipio', 'agravo'], as_index=False).sum()

pop_19['pop_total'] = pop_19['pop_total'] / 12
pop_19['pop_homem'] = pop_19['pop_homem'] / 12
pop_19['pop_mulher'] = pop_19['pop_mulher'] / 12

pop_19['taxa_obitos_total'] = (pop_19['obitos_total'] / pop_19['pop_total']) * 100000
pop_19['taxa_obitos_homem'] = (pop_19['obitos_homem'] / pop_19['pop_homem']) * 100000
pop_19['taxa_obitos_mulher'] = (pop_19['obitos_mulher'] / pop_19['pop_mulher']) * 100000

pop_19['taxa_obitos_esp_total'] = (pop_19['obitos_esp_total'] / pop_pad_t) * 100000
pop_19['taxa_obitos_esp_homem'] = (pop_19['obitos_esp_homem'] / pop_pad_h) * 100000
pop_19['taxa_obitos_esp_mulher'] = (pop_19['obitos_esp_mulher'] / pop_pad_m) * 100000

In [33]:
df_pos_media = pop_19[['agravo', 'taxa_obitos_esp_total']].groupby(['agravo'], as_index=False).mean()
df_pos_dp = pop_19[['agravo', 'taxa_obitos_esp_total']].groupby(['agravo'], as_index=False).std()

aux_pos = df_pos_media.merge(df_pos_dp, on=['agravo'])
aux_pos.columns = ['agravo', 'media_pos', 'dp_pos']

pd.set_option('display.max_rows', 100)

aux = aux_pre.merge(aux_pos, on=['agravo'])

In [34]:
aux.set_index("agravo", inplace=True)

ordem = ['tbgenurin', 'tubresp', 'diarreia', 'chagas', 'leishteg', 'odip',
        'leishvisc', 'outrasiibac', 'dengue', 'esquisto', 'lepto', 'cisticercose',
        'salmonela', 'tbmiliar', 'amebiase', 'tbintestino', 'infecvirais',
        'colera', 'febreenter', 'shiguelose', 'protozoarios', 'tbsistnerv',
        'tbossea', 'febreamarela', 'hepatitea', 'malaria', 'outraleish',
        'equinoco', 'teniase', 'filariose', 'ancilosto', 'ascaridiase',
        'estrongilo', 'tricuriose', 'enterobiose', 'tracoma', 'micose',
        'conjuntivite', 'dermato', 'diabetesm', 'transtafetivos', 'tmusopsico',
        'transtneuro', 'conjuntivinv', 'hipertensao', 'dhipert', 'iamrecor',
        'doenisquem', 'doecv', 'asma', 'broncoeq', 'pneumoco', 'outrasdavai',
        'bronquite', 'doencviaaer', 'outradoenresp', 'outraspele', 'doenpele',
        'infecpele', 'insufrenal', 'infecespperi', 'extintind', 'extmorbmort',
        'exttrauma', 'homicidio', 'suicidio', 'acidente', 'veneno', 'naturais', 'externas', 'total']
         

tabela = aux.reindex(ordem).round(2)
tabela
#tabela.to_csv('tabela.csv', sep=' ')

                media_pre  dp_pre  media_pos  dp_pos
agravo
tbgenurin            0.01    0.12       0.00    0.03
tubresp              0.87    1.16       0.72    3.07
diarreia             1.40    1.34       1.68    4.99
chagas               6.62    6.82       6.22   18.54
leishteg             0.01    0.11       0.01    0.14
odip                 0.16    0.32       0.14    0.72
leishvisc            0.14    0.27       0.41    3.68
outrasiibac          0.07    0.24       0.04    0.28
dengue               0.39    0.62       0.99    2.71
esquisto             0.17    0.34       0.23    0.82
lepto                0.03    0.11       0.01    0.06
cisticercose         0.08    0.27       0.04    0.41
salmonela            0.00    0.00       0.00    0.01
tbmiliar             0.02    0.06       0.02    0.18
amebiase             0.04    0.17       0.01    0.08
tbintestino          0.01    0.11       0.00    0.00
infecvirais          0.05    0.16       0.10    0.61
colera               0.00    0.00       0.00    0.00
febreenter           0.00    0.00       0.00    0.00
shiguelose           0.00    0.01       0.00    0.00
protozoarios         0.00    0.04       0.00    0.00
tbsistnerv           0.02    0.10       0.00    0.00
tbossea              0.00    0.01       0.00    0.00
febreamarela         0.12    0.43       0.00    0.00
hepatitea            0.03    0.27       0.00    0.00
malaria              0.00    0.03       0.00    0.00
outraleish           0.00    0.03       0.00    0.00
equinoco             0.00    0.00       0.00    0.00
teniase              0.00    0.00       0.00    0.00
filariose            0.00    0.01       0.00    0.00
ancilosto            0.00    0.00       0.00    0.00
ascaridiase          0.00    0.00       0.00    0.00
estrongilo           0.00    0.02       0.00    0.00
tricuriose           0.00    0.00       0.00    0.00
enterobiose          0.00    0.00       0.00    0.00
tracoma              0.00    0.00       0.00    0.00
micose               0.00    0.00       0.00    0.00
conjuntivite         0.00    0.00       0.00    0.00
dermato              0.00    0.00       0.00    0.00
diabetesm           21.97    8.33      19.67   14.42
transtafetivos       0.23    0.42       0.48    1.68
tmusopsico           6.65    3.68       9.86   12.36
transtneuro          0.02    0.09       0.00    0.02
conjuntivinv         0.00    0.00       0.00    0.00
hipertensao         11.86    6.01      13.57   11.22
dhipert             21.55    8.08      22.39   14.56
iamrecor            29.10   10.48      25.73   17.90
doenisquem          34.48   11.58      30.95   18.41
doecv               41.80    9.59      34.42   15.00
asma                 1.30    1.54       1.42    3.72
broncoeq             0.10    0.35       0.01    0.07
pneumoco             0.74    2.54       0.30    1.17
outrasdavai          0.30    0.98       0.26    1.23
bronquite           22.09    6.96      22.55   15.47
doencviaaer         23.50    7.02      23.98   15.24
outradoenresp        0.36    1.94       0.06    0.23
outraspele           1.20    0.99       1.67    3.70
doenpele             1.86    1.36       2.67    4.51
infecpele            0.52    0.66       0.88    2.19
insufrenal           4.56    3.11       4.23    5.75
infecespperi         1.57    1.79       1.63    4.01
extintind            9.92    9.80       9.04   13.44
extmorbmort          0.20    0.52       0.37    1.98
exttrauma           12.68    4.69      17.86   35.31
homicidio           17.28   12.31      13.47   13.33
suicidio             7.22    5.28       9.00   10.66
acidente            22.86    8.96      17.30   17.96
veneno               0.17    0.46       0.27    0.90
naturais           483.32   55.49     465.62   83.62
externas            70.89   18.07      67.39   43.46
total              554.21   62.03     533.01   96.55

In [2]:
df = pd.read_csv("taxa_sih.csv", encoding='latin1')

df

,municipio,id_municipio,ano,mes,agravo,grupo,pop_total,pop_pad_total,pop_homem,pop_pad_homem,pop_mulher,pop_pad_mulher,inter_total,inter_homem,inter_mulher,taxa_inter_total,taxa_inter_homem,taxa_inter_mulher
0,AbaetÃ©,310020,2010,1,acidente,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
1,AbaetÃ©,310020,2010,1,amebiase,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
2,AbaetÃ©,310020,2010,1,ancilosto,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
3,AbaetÃ©,310020,2010,1,ascaridiase,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
4,AbaetÃ©,310020,2010,1,asma,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875995,Vespasiano,317120,2019,12,transtafetivos,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875996,Vespasiano,317120,2019,12,transtneuro,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875997,Vespasiano,317120,2019,12,tricuriose,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875998,Vespasiano,317120,2019,12,tubresp,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875999,Vespasiano,317120,2019,12,veneno,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0

In [3]:
df_r = df[df['ano'] != 2019]
pop_r = df_r.groupby(['municipio', 'id_municipio', 'agravo'], as_index=False).sum()

pop_r['pop_total'] = pop_r['pop_total'] / 12
pop_r['pop_homem'] = pop_r['pop_homem'] / 12
pop_r['pop_mulher'] = pop_r['pop_mulher'] / 12

pop_r['taxa_inter_total'] = (pop_r['inter_total'] / pop_r['pop_total']) * 100000
pop_r['taxa_inter_homem'] = (pop_r['inter_homem'] / pop_r['pop_homem']) * 100000
pop_r['taxa_inter_mulher'] = (pop_r['inter_mulher'] / pop_r['pop_mulher']) * 100000

In [4]:
df_pre_media = pop_r[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).mean()
df_pre_dp = pop_r[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).std()

aux_pre = df_pre_media.merge(df_pre_dp, on=['agravo'])
aux_pre.columns = ['agravo', 'media_pre', 'dp_pre']

In [5]:
df_19 = df[df['ano'] == 2019]
pop_19 = df_19.groupby(['municipio', 'id_municipio', 'ano', 'agravo'], as_index=False).sum()

pop_19['pop_total'] = pop_19['pop_total'] / 12
pop_19['pop_homem'] = pop_19['pop_homem'] / 12
pop_19['pop_mulher'] = pop_19['pop_mulher'] / 12

pop_19['taxa_inter_total'] = (pop_19['inter_total'] / pop_19['pop_total']) * 100000
pop_19['taxa_inter_homem'] = (pop_19['inter_homem'] / pop_19['pop_homem']) * 100000
pop_19['taxa_inter_mulher'] = (pop_19['inter_mulher'] / pop_19['pop_mulher']) * 100000

In [6]:
df_pos_media = pop_19[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).mean()
df_pos_dp = pop_19[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).std()

aux_pos = df_pos_media.merge(df_pos_dp, on=['agravo'])
aux_pos.columns = ['agravo', 'media_pos', 'dp_pos']

pd.set_option('display.max_rows', 100)

aux = aux_pre.merge(aux_pos, on=['agravo'])
aux

            agravo    media_pre       dp_pre    media_pos       dp_pos
0         acidente     0.020578     0.099407     0.000000     0.000000
1         amebiase     0.858317     4.996482     0.007837     0.078369
2        ancilosto     0.000742     0.006568     0.000000     0.000000
3      ascaridiase     0.013436     0.075111     0.000000     0.000000
4             asma    35.271212    33.509442    33.340699    38.555456
5         broncoeq     0.215560     0.505490     0.131943     0.594155
6        bronquite    86.071816    69.584651    87.627963    96.530795
7           chagas     0.393280     0.926447     0.543825     3.391163
8     cisticercose     0.121846     0.317538     0.116213     1.128345
9           colera     0.321857     0.668088     0.521228     1.851719
10    conjuntivinv     0.375986     0.921582     0.105214     0.764742
11    conjuntivite     0.018769     0.093003     0.023172     0.199585
12          dengue    26.930472    40.813751    50.941756    57.687594
13         dermato     0.008404     0.053421     0.051108     0.427252
14         dhipert    33.670178    49.688452    17.845745    38.797665
15       diabetesm    67.363842    67.113251    63.648158    66.125443
16        diarreia    32.759986    57.549113    25.875127    56.086787
17           doecv   108.690773    43.676960   117.538224    58.096740
18     doencviaaer   121.558588    88.052067   121.100605   115.809871
19      doenisquem   122.797742    44.169666   134.802048    85.007342
20        doenpele    86.424043    39.383990    80.690231    53.406015
21     enterobiose     0.000000     0.000000     0.000398     0.003981
22        equinoco     0.000045     0.000452     0.000000     0.000000
23        esquisto     0.176605     0.389453     0.437409     3.650859
24      estrongilo     0.001573     0.010319     0.000000     0.000000
25        externas   542.590872   115.729436   587.646254   192.668228
26      externas_S   415.727963    85.291071   463.203152   142.239630
27      externas_T   126.862909    43.796377   124.443102    79.608441
28       extintind     0.015894     0.067919     0.000000     0.000000
29     extmorbmort     0.052517     0.199815     0.000000     0.000000
30       exttrauma     0.159275     0.545758     0.000000     0.000000
31    febreamarela     0.672586     1.617964     0.000398     0.003981
32      febreenter     0.014400     0.074304     0.061147     0.611471
33       filariose     0.085220     0.383366     0.003868     0.027646
34       hepatitea     0.113311     0.439518     0.288365     2.309444
35     hipertensao    23.732424    45.118887    11.890244    36.927392
36       homicidio     0.081499     0.352467     0.000000     0.000000
37        iamrecor    52.519983    20.756690    67.264223    46.361402
38    infecespperi     7.668104     5.494621     9.349434    11.147289
39       infecpele    24.678746    28.014521    23.919631    23.578612
40     infecvirais     6.230078    11.159017     3.099182     9.466048
41      insufrenal    46.091697    21.818364    53.439464    38.872117
42        leishteg     0.641057     1.602203     1.455213     4.754294
43       leishvisc     1.324617     2.073408     1.965726     6.781348
44           lepto     0.438389     1.118121     0.530905     3.105775
45         malaria     0.022673     0.089443     0.048402     0.431980
46          micose     0.060210     0.260806     0.003384     0.030088
47        naturais  4887.025832  1310.059949  4897.175483  1474.026244
48            odip    16.314798    26.986586     7.214682    14.444431
49   outradoenresp    45.260612    30.949855    28.310907    30.742992
50      outraleish     0.274530     0.637769     0.185220     0.878635
51     outrasdavai    19.593937    17.022989    25.224403    23.766206
52     outrasiibac     6.424252    10.375445     3.183898     7.424217
53      outraspele    56.467359    27.316483    51.783089    38.459421
54        pneumoco     0.218860     0.404468     0.204500     1.007831
55    protozoarios     2.451646    13.223003     0.558323     3.118404
56       salmonela     0.306697     1.127340     0.158520     1.141144
57      shiguelose     0.029407     0.158954     0.145776     0.804345
58        suicidio     0.052998     0.239409     0.000000     0.000000
59       tbgenurin     0.006883     0.044019     0.000000     0.000000
60     tbintestino     0.018378     0.105717     0.000000     0.000000
61        tbmiliar     0.169576     0.610591     0.115307     0.551872
62         tbossea     0.030653     0.176917     0.001990     0.019904
63      tbsistnerv     0.098530     0.372518     0.011335     0.105606
64         teniase     0.004076     0.040756     0.000000     0.000000
65      tmusopsico    30.133305    31.283709    27.579611    50.751511
66           total  5430.427882  1344.002407  5484.821738  1548.885709
67         tracoma     0.011557     0.110299     0.000000     0.000000
68  transtafetivos    14.107118    13.723336    27.236428    46.682137
69     transtneuro     1.103829     2.287688     1.022268     2.585949
70      tricuriose     0.000000     0.000000     0.000000     0.000000
71         tubresp     3.811517     5.090477     4.051789    11.108246
72          veneno     0.000045     0.000452     0.000000     0.000000

In [7]:
aux.set_index("agravo", inplace=True)

ordem = ['enterobiose', 'tricuriose', 'shiguelose', 'ancilosto', 'dermato', 'conjuntivite', 'estrongilo',
        'leishteg', 'dengue', 'tbossea', 'malaria', 'tbmiliar', 'hepatitea',
        'esquisto', 'micose', 'leishvisc', 'chagas', 'diarreia',
        'lepto', 'outraleish', 'filariose', 'colera', 'outrasiibac',
        'infecvirais', 'odip', 'tbsistnerv', 'febreenter', 'cisticercose',
        'salmonela', 'protozoarios', 'amebiase', 'febreamarela', 'teniase',
        'equinoco', 'tracoma', 'tbgenurin', 'tbintestino', 'tubresp',
        'ascaridiase', 'diabetesm', 'transtafetivos', 'transtneuro', 'tmusopsico',
        'conjuntivinv', 'iamrecor', 'doenisquem', 'doecv',
        'dhipert', 'hipertensao', 'outrasdavai', 'broncoeq', 'pneumoco',
        'bronquite', 'doencviaaer', 'asma', 'outradoenresp', 'infecpele', 'doenpele',
        'outraspele', 'insufrenal', 'infecespperi', 'veneno', 'extmorbmort',
        'extintind', 'exttrauma', 'homicidio', 'suicidio', 'acidente', 'naturais', 'externas', 'total']
         

tabela = aux.reindex(ordem).round(2)
tabela

                media_pre   dp_pre  media_pos   dp_pos
agravo
enterobiose          0.00     0.00       0.00     0.00
tricuriose           0.00     0.00       0.00     0.00
shiguelose           0.03     0.16       0.15     0.80
ancilosto            0.00     0.01       0.00     0.00
dermato              0.01     0.05       0.05     0.43
conjuntivite         0.02     0.09       0.02     0.20
estrongilo           0.00     0.01       0.00     0.00
leishteg             0.64     1.60       1.46     4.75
dengue              26.93    40.81      50.94    57.69
tbossea              0.03     0.18       0.00     0.02
malaria              0.02     0.09       0.05     0.43
tbmiliar             0.17     0.61       0.12     0.55
hepatitea            0.11     0.44       0.29     2.31
esquisto             0.18     0.39       0.44     3.65
micose               0.06     0.26       0.00     0.03
leishvisc            1.32     2.07       1.97     6.78
chagas               0.39     0.93       0.54     3.39
diarreia            32.76    57.55      25.88    56.09
lepto                0.44     1.12       0.53     3.11
outraleish           0.27     0.64       0.19     0.88
filariose            0.09     0.38       0.00     0.03
colera               0.32     0.67       0.52     1.85
outrasiibac          6.42    10.38       3.18     7.42
infecvirais          6.23    11.16       3.10     9.47
odip                16.31    26.99       7.21    14.44
tbsistnerv           0.10     0.37       0.01     0.11
febreenter           0.01     0.07       0.06     0.61
cisticercose         0.12     0.32       0.12     1.13
salmonela            0.31     1.13       0.16     1.14
protozoarios         2.45    13.22       0.56     3.12
amebiase             0.86     5.00       0.01     0.08
febreamarela         0.67     1.62       0.00     0.00
teniase              0.00     0.04       0.00     0.00
equinoco             0.00     0.00       0.00     0.00
tracoma              0.01     0.11       0.00     0.00
tbgenurin            0.01     0.04       0.00     0.00
tbintestino          0.02     0.11       0.00     0.00
tubresp              3.81     5.09       4.05    11.11
ascaridiase          0.01     0.08       0.00     0.00
diabetesm           67.36    67.11      63.65    66.13
transtafetivos      14.11    13.72      27.24    46.68
transtneuro          1.10     2.29       1.02     2.59
tmusopsico          30.13    31.28      27.58    50.75
conjuntivinv         0.38     0.92       0.11     0.76
iamrecor            52.52    20.76      67.26    46.36
doenisquem         122.80    44.17     134.80    85.01
doecv              108.69    43.68     117.54    58.10
dhipert             33.67    49.69      17.85    38.80
hipertensao         23.73    45.12      11.89    36.93
outrasdavai         19.59    17.02      25.22    23.77
broncoeq             0.22     0.51       0.13     0.59
pneumoco             0.22     0.40       0.20     1.01
bronquite           86.07    69.58      87.63    96.53
doencviaaer        121.56    88.05     121.10   115.81
asma                35.27    33.51      33.34    38.56
outradoenresp       45.26    30.95      28.31    30.74
infecpele           24.68    28.01      23.92    23.58
doenpele            86.42    39.38      80.69    53.41
outraspele          56.47    27.32      51.78    38.46
insufrenal          46.09    21.82      53.44    38.87
infecespperi         7.67     5.49       9.35    11.15
veneno               0.00     0.00       0.00     0.00
extmorbmort          0.05     0.20       0.00     0.00
extintind            0.02     0.07       0.00     0.00
exttrauma            0.16     0.55       0.00     0.00
homicidio            0.08     0.35       0.00     0.00
suicidio             0.05     0.24       0.00     0.00
acidente             0.02     0.10       0.00     0.00
naturais          4887.03  1310.06    4897.18  1474.03
externas           542.59   115.73     587.65   192.67
total             5430.43  1344.00    5484.82  1548.89

In [8]:
df = pd.read_csv("taxa_sinan.csv", encoding='latin1')

df

,municipio,id_municipio,ano,mes,agravo,grupo,pop_total,pop_pad_total,pop_homem,pop_pad_homem,pop_mulher,pop_pad_mulher,notificacoes_total,notificacoes_homem,notificacoes_mulher,taxa_notific_total,taxa_notific_homem,taxa_notific_mulher
0,AbaetÃ©,310020,2013,1,chagas,2,23151,19957444,11477,9828254,11674,10129190,0,0,0,0.000000,0.00000,0.000000
1,AbaetÃ©,310020,2013,1,colera,2,23151,19957444,11477,9828254,11674,10129190,0,0,0,0.000000,0.00000,0.000000
2,AbaetÃ©,310020,2013,1,dengue,2,23151,19957444,11477,9828254,11674,10129190,0,0,0,0.000000,0.00000,0.000000
3,AbaetÃ©,310020,2013,1,esquisto,2,23151,19957444,11477,9828254,11674,10129190,0,0,0,0.000000,0.00000,0.000000
4,AbaetÃ©,310020,2013,1,febreamarela,2,23151,19957444,11477,9828254,11674,10129190,0,0,0,0.000000,0.00000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117595,Vespasiano,317120,2019,12,leishvisc,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.000000,0.00000,0.000000
117596,Vespasiano,317120,2019,12,lepto,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.000000,0.00000,0.000000
117597,Vespasiano,317120,2019,12,malaria,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.000000,0.00000,0.000000
117598,Vespasiano,317120,2019,12,sindrome,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.000000,0.00000,0.000000
117599,Vespasiano,317120,2019,12,tubresp,3,127601,19957444,61757,9828254,65844,10129190,2,1,1,1.567386,1.61925,1.518741

In [75]:
df_r = df[df['ano'] != 2019]
pop_r = df_r.groupby(['municipio', 'id_municipio', 'agravo'], as_index=False).sum()

pop_r['pop_total'] = pop_r['pop_total'] / 12

pop_r['taxa_notific_total'] = (pop_r['notificacoes_total'] / pop_r['pop_total']) * 100000

In [76]:
df_pre_media = pop_r[['agravo', 'taxa_notific_total']].groupby(['agravo'], as_index=False).mean()
df_pre_dp = pop_r[['agravo', 'taxa_notific_total']].groupby(['agravo'], as_index=False).std()

aux_pre = df_pre_media.merge(df_pre_dp, on=['agravo'])
aux_pre.columns = ['agravo', 'media_pre', 'dp_pre']

In [77]:
df_19 = df[df['ano'] == 2019]
pop_19 = df_19.groupby(['municipio', 'id_municipio', 'ano', 'agravo'], as_index=False).sum()

pop_19['pop_total'] = pop_19['pop_total'] / 12

pop_19['taxa_inter_total'] = (pop_19['notificacoes_total'] / pop_19['pop_total']) * 100000

In [79]:
df_pos_media = pop_19[['agravo', 'taxa_notific_total']].groupby(['agravo'], as_index=False).mean()
df_pos_dp = pop_19[['agravo', 'taxa_notific_total']].groupby(['agravo'], as_index=False).std()

aux_pos = df_pos_media.merge(df_pos_dp, on=['agravo'])
aux_pos.columns = ['agravo', 'media_pos', 'dp_pos']

pd.set_option('display.max_rows', 100)

aux = aux_pre.merge(aux_pos, on=['agravo'])

tabela = aux.round(4)

tabela

          agravo  media_pre    dp_pre  media_pos     dp_pos
0         chagas     0.0000    0.0000     0.0000     0.0000
1         colera     0.0000    0.0000     0.0000     0.0000
2         dengue   662.2408  540.4828  1816.0865  1949.0312
3       esquisto     5.8501   11.5627     0.0000     0.0000
4   febreamarela     0.0000    0.0000     0.0000     0.0000
5       febretif     0.0042    0.0302     0.0000     0.0000
6      homicidio    71.7124   72.9388     0.0000     0.0000
7    intoxicacao    53.1774   63.5307    63.4706    77.1292
8       leishteg     9.1741   10.7025     0.0000     0.0000
9      leishvisc     2.4925    3.4838     2.5717     6.8103
10         lepto     0.7215    1.7788     1.4002     4.7875
11       malaria     0.1012    0.2484     0.2495     1.0356
12      sindrome     0.0000    0.0000     0.0000     0.0000
13       tubresp     9.0006    6.6830    12.9915    13.8820

In [80]:
df = pd.read_csv("taxa_sih_cap.csv", encoding='latin1')

df

,municipio,id_municipio,ano,mes,capitulo,grupo,pop_total,pop_pad_total,pop_homem,pop_pad_homem,pop_mulher,pop_pad_mulher,inter_total,inter_homem,inter_mulher,taxa_inter_total,taxa_inter_homem,taxa_inter_mulher
0,AbaetÃ©,310020,2010,1,I,2,23107,19957444,11442,9828254,11665,10129190,4,2,2,17.310772,17.479462,17.145306
1,AbaetÃ©,310020,2010,1,IV,2,23107,19957444,11442,9828254,11665,10129190,7,3,4,30.293850,26.219192,34.290613
2,AbaetÃ©,310020,2010,1,IX,2,23107,19957444,11442,9828254,11665,10129190,14,9,5,60.587701,78.657577,42.863266
3,AbaetÃ©,310020,2010,1,V,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.000000,0.000000,0.000000
4,AbaetÃ©,310020,2010,1,X,2,23107,19957444,11442,9828254,11665,10129190,3,2,1,12.983079,17.479462,8.572653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107995,Vespasiano,317120,2019,12,X,3,127601,19957444,61757,9828254,65844,10129190,16,9,7,12.539087,14.573247,10.631189
107996,Vespasiano,317120,2019,12,XII,3,127601,19957444,61757,9828254,65844,10129190,11,3,8,8.620622,4.857749,12.149930
107997,Vespasiano,317120,2019,12,XIV,3,127601,19957444,61757,9828254,65844,10129190,9,6,3,7.053236,9.715498,4.556224
107998,Vespasiano,317120,2019,12,XVI,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.000000,0.000000,0.000000
107999,Vespasiano,317120,2019,12,XX,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.000000,0.000000,0.000000

In [81]:
df_r = df[df['ano'] != 2019]
pop_r = df_r.groupby(['municipio', 'id_municipio', 'capitulo'], as_index=False).sum()

pop_r['pop_total'] = pop_r['pop_total'] / 12

pop_r['taxa_inter_total'] = (pop_r['inter_total'] / pop_r['pop_total']) * 100000

In [82]:
df_pre_media = pop_r[['capitulo', 'taxa_inter_total']].groupby(['capitulo'], as_index=False).mean()
df_pre_dp = pop_r[['capitulo', 'taxa_inter_total']].groupby(['capitulo'], as_index=False).std()

aux_pre = df_pre_media.merge(df_pre_dp, on=['capitulo'])
aux_pre.columns = ['capitulo', 'media_pre', 'dp_pre']

In [83]:
df_19 = df[df['ano'] == 2019]
pop_19 = df_19.groupby(['municipio', 'id_municipio', 'capitulo'], as_index=False).sum()

pop_19['pop_total'] = pop_19['pop_total'] / 12

pop_19['taxa_inter_total'] = (pop_19['inter_total'] / pop_19['pop_total']) * 100000

In [85]:
df_pos_media = pop_19[['capitulo', 'taxa_inter_total']].groupby(['capitulo'], as_index=False).mean()
df_pos_dp = pop_19[['capitulo', 'taxa_inter_total']].groupby(['capitulo'], as_index=False).std()

aux_pos = df_pos_media.merge(df_pos_dp, on=['capitulo'])
aux_pos.columns = ['capitulo', 'media_pos', 'dp_pos']

pd.set_option('display.max_rows', 100)

aux = aux_pre.merge(aux_pos, on=['capitulo'])
aux.round(4)

  capitulo  media_pre    dp_pre  media_pos    dp_pos
0        I    84.8456   99.2840    94.3868   93.4616
1       IV    67.3638   67.1133    63.6482   66.1254
2       IX   265.1587  111.5892   270.1860  127.2793
3        V    45.3443   40.3773    55.8383   84.1911
4        X   186.6320  103.1335   174.8404  129.8150
5      XII    86.4240   39.3840    80.6902   53.4060
6      XIV    46.0917   21.8184    53.4395   38.8721
7      XVI     7.6681    5.4946     9.3494   11.1473
8       XX     0.3298    0.7299     0.0000    0.0000

In [86]:
df = pd.read_csv("taxa_sim_cap.csv", encoding='latin1')

df

,municipio,id_municipio,ano,mes,capitulo,grupo,pop_total,pop_pad_total,pop_homem,pop_pad_homem,...,obitos_mulher,taxa_obitos_total,taxa_obitos_homem,taxa_obitos_mulher,obitos_esp_total,obitos_esp_homem,obitos_esp_mulher,taxa_obitos_esp_total,taxa_obitos_esp_homem,taxa_obitos_esp_mulher
0,AbaetÃ©,310020,2010,1,I,2,23107,19957444,11442,9828254,...,0,0.000000,0.000000,0.000000,0.0000,0.00000,0.00000,0.000000,0.000000,0.000000
1,AbaetÃ©,310020,2010,1,IV,2,23107,19957444,11442,9828254,...,0,0.000000,0.000000,0.000000,0.0000,0.00000,0.00000,0.000000,0.000000,0.000000
2,AbaetÃ©,310020,2010,1,IX,2,23107,19957444,11442,9828254,...,1,12.983079,17.479462,8.572653,2111.5150,1405.49880,705.31650,10.580087,14.300595,6.963208
3,AbaetÃ©,310020,2010,1,V,2,23107,19957444,11442,9828254,...,0,0.000000,0.000000,0.000000,0.0000,0.00000,0.00000,0.000000,0.000000,0.000000
4,AbaetÃ©,310020,2010,1,X,2,23107,19957444,11442,9828254,...,0,0.000000,0.000000,0.000000,0.0000,0.00000,0.00000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107995,Vespasiano,317120,2019,12,X,3,127601,19957444,61757,9828254,...,1,1.567386,1.619250,1.518741,412.0229,203.19540,209.50050,2.064507,2.067462,2.068285
107996,Vespasiano,317120,2019,12,XII,3,127601,19957444,61757,9828254,...,0,0.000000,0.000000,0.000000,0.0000,0.00000,0.00000,0.000000,0.000000,0.000000
107997,Vespasiano,317120,2019,12,XIV,3,127601,19957444,61757,9828254,...,0,0.000000,0.000000,0.000000,0.0000,0.00000,0.00000,0.000000,0.000000,0.000000
107998,Vespasiano,317120,2019,12,XVI,3,127601,19957444,61757,9828254,...,0,0.000000,0.000000,0.000000,0.0000,0.00000,0.00000,0.000000,0.000000,0.000000
107999,Vespasiano,317120,2019,12,XX,3,127601,19957444,61757,9828254,...,1,4.702158,8.096248,1.518741,992.6306,857.37146,161.12503,4.973736,8.723538,1.590700

In [90]:
pop_pad_t = df['pop_pad_total'].unique().sum()
pop_pad_h = df['pop_pad_homem'].unique().sum()
pop_pad_m = df['pop_pad_mulher'].unique().sum()

In [91]:
df_r = df[df['ano'] != 2019]
pop_r = df_r.groupby(['municipio', 'id_municipio', 'capitulo'], as_index=False).sum()

pop_r['pop_total'] = pop_r['pop_total'] / 12

pop_r['taxa_obitos_total'] = (pop_r['obitos_total'] / pop_r['pop_total']) * 100000

pop_r['taxa_obitos_esp_total'] = (pop_r['obitos_esp_total'] / (pop_pad_t * 9)) * 100000

In [92]:
df_pre_media = pop_r[['capitulo', 'taxa_obitos_esp_total']].groupby(['capitulo'], as_index=False).mean()
df_pre_dp = pop_r[['capitulo', 'taxa_obitos_esp_total']].groupby(['capitulo'], as_index=False).std()

aux_pre = df_pre_media.merge(df_pre_dp, on=['capitulo'])
aux_pre.columns = ['capitulo', 'media_pre', 'dp_pre']

In [93]:
df_19 = df[df['ano'] == 2019]
pop_19 = df_19.groupby(['municipio', 'id_municipio', 'ano', 'capitulo'], as_index=False).sum()

pop_19['pop_total'] = pop_19['pop_total'] / 12

pop_19['taxa_obitos_total'] = (pop_19['obitos_total'] / pop_19['pop_total']) * 100000

pop_19['taxa_obitos_esp_total'] = (pop_19['obitos_esp_total'] / pop_pad_t) * 100000

In [94]:
df_pos_media = pop_19[['capitulo', 'taxa_obitos_esp_total']].groupby(['capitulo'], as_index=False).mean()
df_pos_dp = pop_19[['capitulo', 'taxa_obitos_esp_total']].groupby(['capitulo'], as_index=False).std()

aux_pos = df_pos_media.merge(df_pos_dp, on=['capitulo'])
aux_pos.columns = ['capitulo', 'media_pos', 'dp_pos']

pd.set_option('display.max_rows', 100)

aux = aux_pre.merge(aux_pos, on=['capitulo'])
aux.round(4)

  capitulo  media_pre   dp_pre  media_pos   dp_pos
0        I    10.0863   6.9456    10.4879  23.0807
1       IV    21.9732   8.3308    19.6688  14.4200
2       IX    97.8292  19.2350    87.7576  31.4200
3        V     6.8959   3.7722    10.3461  12.5167
4        X    24.8995   7.2135    24.5930  15.4629
5      XII     1.8571   1.3592     2.6685   4.5069
6      XIV     4.5605   3.1114     4.2331   5.7477
7      XVI     1.5689   1.7927     1.6345   4.0061
8       XX    70.1610  17.8714    67.0367  43.4436

In [51]:
letras = ['S', 'T', 'V', 'W', 'X', 'Y']

sih = pd.read_csv('sih_agravos.csv')

sih = sih[(sih['MUNIC_RES'].isin(municipios)) & (sih['DIAG_SECUN'].str[0].isin(letras))]

sih

c:\users\lucas\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (8,26) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,IDENT,MUNIC_RES,MUNIC_MOV,NASC,SEXO,DT_INTER,DT_SAIDA,DIAG_PRINC,DIAG_SECUN,COD_IDADE,...,idade2,faixaetaria,sexo2,raca2,esc,causa3,agravo,subgrupo,semana,capitulo
105,1,313190,313190,19831011,1,20100105,20100107,T630,W010,4,...,26,25a29,M,NaN,NaN,T63,externas,externas_T,NaN,XIX
434,1,314610,314000,19800822,1,20100127,20100129,T141,W999,4,...,29,25a29,M,NaN,NaN,T14,externas,externas_T,NaN,XIX
548,1,313190,313190,19410919,3,20100110,20100115,T630,W010,4,...,68,65a69,F,NaN,NaN,T63,externas,externas_T,NaN,XIX
1081,1,313190,313190,19791026,1,20100103,20100106,S623,W010,4,...,30,30a34,M,NaN,NaN,S62,externas,externas_S,NaN,XIX
1202,1,313190,313190,19520304,1,20100117,20100119,S962,W010,4,...,57,55a59,M,NaN,NaN,S96,externas,externas_S,NaN,XIX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5949689,1,316210,317020,19690902,1,20141202,20141220,T861,Y849,4,...,45,45a49,M,Parda,NaN,T86,externas,externas_T,NaN,XIX
5950926,1,316210,317020,19440108,3,20141112,20141114,T813,Y831,4,...,70,70a74,F,Branca,NaN,T81,externas,externas_T,NaN,XIX
5952675,1,316210,317020,19610804,1,20141217,20141218,S059,W449,4,...,53,50a54,M,Branca,NaN,S05,externas,externas_S,NaN,XIX
5952772,1,313810,317080,19780822,1,20141209,20141214,S017,W188,4,...,36,35a39,M,NaN,NaN,S01,externas,externas_S,NaN,XIX
5952898,1,316295,317120,19870327,1,20141209,20141216,T519,Y800,4,...,27,25a29,M,NaN,NaN,T51,externas,externas_T,NaN,XIX

In [86]:
causas = sih[sih['subgrupo'] == 'externas_T']['DIAG_PRINC'].unique()

sih[(sih['ano_inter'] == 2019) & (sih['DIAG_SECUN'].isin(causas))]['IDADE'].count()

0

In [8]:
df_sih = pd.read_csv('taxa_sih.csv')

df_sih

,municipio,id_municipio,ano,mes,agravo,grupo,pop_total,pop_pad_total,pop_homem,pop_pad_homem,pop_mulher,pop_pad_mulher,inter_total,inter_homem,inter_mulher,taxa_inter_total,taxa_inter_homem,taxa_inter_mulher
0,Abaeté,310020,2010,1,acidente,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
1,Abaeté,310020,2010,1,amebiase,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
2,Abaeté,310020,2010,1,ancilosto,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
3,Abaeté,310020,2010,1,ascaridiase,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
4,Abaeté,310020,2010,1,asma,2,23107,19957444,11442,9828254,11665,10129190,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875995,Vespasiano,317120,2019,12,transtafetivos,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875996,Vespasiano,317120,2019,12,transtneuro,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875997,Vespasiano,317120,2019,12,tricuriose,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875998,Vespasiano,317120,2019,12,tubresp,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0
875999,Vespasiano,317120,2019,12,veneno,3,127601,19957444,61757,9828254,65844,10129190,0,0,0,0.0,0.0,0.0

In [10]:
df_sih_pre = df_sih[df_sih['ano'] != 2019]
df_sih_pre[['agravo', 'inter_total']].groupby(['agravo']).sum()

                inter_total
agravo
acidente                 19
amebiase                158
ancilosto                 3
ascaridiase              24
asma                  36957
broncoeq                205
bronquite             31101
chagas                  127
cisticercose             97
colera                  256
conjuntivinv            226
conjuntivite             15
dengue                11893
dermato                  17
dhipert                9543
diabetesm             30813
diarreia              11043
doecv                 55545
doencviaaer           68263
doenisquem            71695
doenpele              56500
enterobiose               0
equinoco                  1
esquisto                174
estrongilo                5
externas             345716
externas_S           264183
externas_T            81533
extintind                11
extmorbmort             118
exttrauma               108
febreamarela            222
febreenter               23
filariose                56
hepatitea                74
hipertensao            6359
homicidio                42
iamrecor              30557
infecespperi           5982
infecpele             13456
infecvirais            1930
insufrenal            32763
leishteg                230
leishvisc               946
lepto                   256
malaria                  38
micose                   18
naturais            2710141
odip                   6893
outradoenresp         32385
outraleish              170
outrasdavai           16225
outrasiibac            4383
outraspele            39593
pneumoco                137
protozoarios            258
salmonela               124
shiguelose               17
suicidio                 23
tbgenurin                10
tbintestino              10
tbmiliar                 82
tbossea                  15
tbsistnerv               56
teniase                   1
tmusopsico            19612
total               3056484
tracoma                   3
transtafetivos         6543
transtneuro             626
tricuriose                0
tubresp                3978
veneno                    1

In [13]:
df_sih_pos = df_sih[df_sih['ano'] == 2019]
df_sih_pos[['agravo', 'inter_total']].groupby(['agravo']).sum()

                inter_total
agravo
acidente                  0
amebiase                  1
ancilosto                 0
ascaridiase               0
asma                   3599
broncoeq                 30
bronquite              3746
chagas                   14
cisticercose              3
colera                   16
conjuntivinv             17
conjuntivite              4
dengue                 4417
dermato                   5
dhipert                 841
diabetesm              4176
diarreia               1266
doecv                  7700
doencviaaer            7375
doenisquem             8621
doenpele               6280
enterobiose               1
equinoco                  0
esquisto                 20
estrongilo                0
externas              39369
externas_S            30282
externas_T             9087
extintind                 0
extmorbmort               0
exttrauma                 0
febreamarela              1
febreenter                1
filariose                 5
hepatitea                 6
hipertensao             467
homicidio                 0
iamrecor               4249
infecespperi            613
infecpele              1781
infecvirais             143
insufrenal             4341
leishteg                 46
leishvisc                73
lepto                    23
malaria                   5
micose                    2
naturais             319898
odip                    400
outradoenresp          2274
outraleish               12
outrasdavai            2275
outrasiibac             229
outraspele             4114
pneumoco                 25
protozoarios             15
salmonela                 3
shiguelose                8
suicidio                  0
tbgenurin                 0
tbintestino               0
tbmiliar                 16
tbossea                   5
tbsistnerv                3
teniase                   0
tmusopsico             1431
total                359267
tracoma                   0
transtafetivos          901
transtneuro              69
tricuriose                0
tubresp                 451
veneno                    0

In [14]:
pd.set_option('display.max_rows', 100)
media = df_pre[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).mean()
media.columns = ['agravo', 'media_pre']

dp = df_pre[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).std()
dp.columns = ['agravo', 'desvio_padrão_pre']


dados_pre = media.merge(dp, on='agravo')

NameError: name 'df_pre' is not defined

In [4]:
pd.set_option('display.max_rows', 100)
media = df_pos[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).mean()
media.columns = ['agravo', 'media_pos']

dp = df_pos[['agravo', 'taxa_inter_total']].groupby(['agravo'], as_index=False).std()
dp.columns = ['agravo', 'desvio_padrão_pos']


dados_pos = media.merge(dp, on='agravo')

In [5]:
#dados_pre.merge(dados_pos, on='agravo')

In [ ]:
total_pre = df_pre[['agravo', 'inter_total']].groupby('agravo', as_index=False).sum()
total_pre.columns = ['agravo', 'intermações_pre']

total_pos = df_pos[['agravo', 'inter_total']].groupby('agravo', as_index=False).sum()
total_pos.columns = ['agravo', 'intermações_pos']

total_pre.merge(total_pos, on='agravo')