In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(f"HEPATITES_Minas_Gerais.csv", encoding='latin1', sep=',')
df

,Município,Código,Nome Município,Casos Total,Hepatite A,Hepatite B,Hepatite C,Hepatite D,Hepatite A Total,Hepatite A 1999-2007,...,Tx Det F Hep B F 2011,Tx Det F Hep B F 2012,Tx Det F Hep B F 2013,Tx Det F Hep B F 2014,Tx Det F Hep B F 2015,Tx Det F Hep B F 2016,Tx Det F Hep B F 2017,Tx Det F Hep B F 2018,Tx Det F Hep B F 2019,Tx Det F Hep B F 2020
0,310010 Abadia dos Dourados,310010,Abadia dos Dourados,13,8,1,4,0,8,4,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
1,310020 Abaeté,310020,Abaeté,13,2,4,7,0,2,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
2,310030 Abre Campo,310030,Abre Campo,7,4,3,0,0,4,0,...,"0,0","0,0","0,0","0,0","14,9","0,0","0,0","0,0","0,0","0,0"
3,310040 Acaiaca,310040,Acaiaca,5,0,2,3,0,0,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","47,5"
4,310050 Açucena,310050,Açucena,8,3,4,1,0,3,1,...,"0,0","20,2","0,0","0,0","0,0","0,0","21,1","21,3","0,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,317180 Virginópolis,317180,Virginópolis,8,3,5,0,0,3,1,...,"0,0","0,0","18,5","0,0","0,0","0,0","0,0","0,0","0,0","18,8"
849,317190 Virgolândia,317190,Virgolândia,16,7,9,0,0,7,7,...,"0,0","0,0","0,0","0,0","0,0","0,0","71,6","0,0","36,3","0,0"
850,317200 Visconde do Rio Branco,317200,Visconde do Rio Branco,15,2,9,4,0,2,2,...,"0,0","5,1","5,0","0,0","4,9","0,0","4,8","0,0","0,0","0,0"
851,317210 Volta Grande,317210,Volta Grande,2,1,1,0,0,1,1,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
852,317220 Wenceslau Braz,317220,Wenceslau Braz,4,4,0,0,0,4,3,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"

In [5]:
#grupos de cidades analisadas
cidades_selecionadas = ["Betim", 'Brumadinho','Curvelo','Esmeraldas','Florestal','Fortuna de Minas',
                        'Igarapé','Juatuba','Maravilhas','Mário Campos','Martinho Campos',
                        'Papagaios','Pará de Minas','Paraopeba','Pequi','Pompéu','São Joaquim de Bicas',
                        'São José da Varginha','Sarzedo']

cidades_limitrofes = ['Abaeté','Araçaí','Belo Horizonte','Belo Vale','Bom Despacho','Bonfim','Cachoeira da Prata',
                      'Caetanópolis','Capim Branco','Conceição do Pará','Contagem','Cordisburgo','Corinto',
                      'Dores do Indaiá','Felixlândia','Ibirité','Igaratinga','Inhaúma','Inimutaba','Itaúna',
                      'Itabirito','Itatiaiuçu','Leandro Ferreira','Mateus Leme','Matozinhos','Moeda',
                      'Morada Nova de Minas','Morro da Garça','Nova Lima','Onça de Pitangui','Paineiras',
                      'Pedro Leopoldo','Pitangui','Presidente Juscelino','Quartel Geral','Ribeirão das Neves',
                      'Rio Manso','Santana de Pirapama','Santo Hipólito','Sete Lagoas']


cidades_prox_limitrofes = ['Araújos','Augusto de Lima','Baldim','Biquinhas','Carmo do Cajuru','Cedro do Abaeté',
                           'Conceição do Mato Dentro','Confins','Congonhas','Congonhas do Norte','Crucilândia',
                           'Estrela do Indaiá','Funilândia','Gouveia','Itaguara','Jaboticatubas','Jeceaba',
                           'Jequitibá','Lagoa Santa','Lassance','Luz','Moema','Monjolos','Nova Serrana',
                           'Ouro Preto','Piedade dos Gerais','Prudente de Morais',
                           'Raposos','Rio Acima','Sabará','São Gonçalo do Abaeté','São Gonçalo do Pará',
                           'São Gotardo','São José da Lapa','Santa Bárbara','Santa Luzia','Santana do Riacho',
                           'Santo Antônio do Monte','Serra da Saudade','Tiros','Vespasiano']


#gera uma lista com o ID de todas as cidades a serem avaliadas
todas = cidades_selecionadas + cidades_limitrofes + cidades_prox_limitrofes

cidades = df[df['Nome Município'].isin(todas)]['Código'].unique()

In [10]:
cidades

array([310020, 310320, 310390, 310480, 310500, 310620, 310640, 310670,
       310700, 310740, 310810, 310900, 310960, 310990, 311250, 311420,
       311560, 311750, 311760, 311787, 311800, 311810, 311860, 311890,
       311910, 312060, 312090, 312320, 312410, 312470, 312570, 312600,
       312640, 312720, 312760, 312980, 313010, 313020, 313100, 313110,
       313190, 313220, 313370, 313380, 313460, 313540, 313570, 313665,
       313760, 313810, 313830, 313880, 313970, 314015, 314050, 314070,
       314110, 314230, 314240, 314250, 314350, 314360, 314480, 314520,
       314580, 314610, 314640, 314690, 314710, 314740, 314930, 314960,
       315040, 315140, 315200, 315320, 315360, 315370, 315390, 315460,
       315480, 315530, 315670, 315720, 315780, 315850, 315900, 316040,
       316060, 316170, 316180, 316210, 316292, 316295, 316310, 316553,
       316660, 316720, 316890, 317120], dtype=int64)

In [11]:
df = df[df['Código'].isin(cidades)]
df

,Município,Código,Nome Município,Casos Total,Hepatite A,Hepatite B,Hepatite C,Hepatite D,Hepatite A Total,Hepatite A 1999-2007,...,Tx Det F Hep B F 2011,Tx Det F Hep B F 2012,Tx Det F Hep B F 2013,Tx Det F Hep B F 2014,Tx Det F Hep B F 2015,Tx Det F Hep B F 2016,Tx Det F Hep B F 2017,Tx Det F Hep B F 2018,Tx Det F Hep B F 2019,Tx Det F Hep B F 2020
1,310020 Abaeté,310020,Abaeté,13,2,4,7,0,2,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
34,310320 Araçaí,310320,Araçaí,7,2,4,1,0,2,2,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
42,310390 Araújos,310390,Araújos,23,18,5,0,0,18,18,...,"0,0","0,0","0,0","0,0","23,2","0,0","0,0","0,0","0,0","0,0"
52,310480 Augusto de Lima,310480,Augusto de Lima,5,2,1,2,0,2,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
54,310500 Baldim,310500,Baldim,2,1,1,0,0,1,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,316553 Sarzedo,316553,Sarzedo,50,3,25,22,0,3,0,...,"15,1","0,0","0,0","20,5","0,0","0,0","0,0","0,0","12,2","11,9"
782,316660 Serra da Saudade,316660,Serra da Saudade,0,0,0,0,0,0,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
789,316720 Sete Lagoas,316720,Sete Lagoas,198,58,57,83,0,58,32,...,"2,7","1,8","0,9","0,9","0,8","0,8","0,0","0,8","0,8","0,0"
807,316890 Tiros,316890,Tiros,17,12,4,0,1,12,11,...,"0,0","30,1","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
842,317120 Vespasiano,317120,Vespasiano,221,27,116,75,3,27,13,...,"1,8","5,4","6,9","1,7","6,6","8,0","4,7","3,1","6,1","1,5"

In [12]:
df.to_csv('hepatite.csv', index=False)