In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(f"HEPATITES_Minas_Gerais.csv", encoding='latin1', sep=',')
df2 = pd.read_csv(f"HEPATITES_Minas_Gerais_2.csv", encoding='latin1', sep=',')

In [2]:
df

,Município,Código,Nome Município,Casos Total,Hepatite A,Hepatite B,Hepatite C,Hepatite D,Hepatite A Total,Hepatite A 1999-2007,...,Tx Det F Hep B F 2011,Tx Det F Hep B F 2012,Tx Det F Hep B F 2013,Tx Det F Hep B F 2014,Tx Det F Hep B F 2015,Tx Det F Hep B F 2016,Tx Det F Hep B F 2017,Tx Det F Hep B F 2018,Tx Det F Hep B F 2019,Tx Det F Hep B F 2020
0,310010 Abadia dos Dourados,310010,Abadia dos Dourados,13,8,1,4,0,8,4,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
1,310020 Abaeté,310020,Abaeté,13,2,4,7,0,2,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
2,310030 Abre Campo,310030,Abre Campo,7,4,3,0,0,4,0,...,"0,0","0,0","0,0","0,0","14,9","0,0","0,0","0,0","0,0","0,0"
3,310040 Acaiaca,310040,Acaiaca,5,0,2,3,0,0,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","47,5"
4,310050 Açucena,310050,Açucena,8,3,4,1,0,3,1,...,"0,0","20,2","0,0","0,0","0,0","0,0","21,1","21,3","0,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,317180 Virginópolis,317180,Virginópolis,8,3,5,0,0,3,1,...,"0,0","0,0","18,5","0,0","0,0","0,0","0,0","0,0","0,0","18,8"
849,317190 Virgolândia,317190,Virgolândia,16,7,9,0,0,7,7,...,"0,0","0,0","0,0","0,0","0,0","0,0","71,6","0,0","36,3","0,0"
850,317200 Visconde do Rio Branco,317200,Visconde do Rio Branco,15,2,9,4,0,2,2,...,"0,0","5,1","5,0","0,0","4,9","0,0","4,8","0,0","0,0","0,0"
851,317210 Volta Grande,317210,Volta Grande,2,1,1,0,0,1,1,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
852,317220 Wenceslau Braz,317220,Wenceslau Braz,4,4,0,0,0,4,3,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"

In [3]:
#grupos de cidades analisadas
cidades_selecionadas = ["Betim", 'Brumadinho','Curvelo','Esmeraldas','Florestal','Fortuna de Minas',
                        'Igarapé','Juatuba','Maravilhas','Mário Campos','Martinho Campos',
                        'Papagaios','Pará de Minas','Paraopeba','Pequi','Pompéu','São Joaquim de Bicas',
                        'São José da Varginha','Sarzedo']

cidades_limitrofes = ['Abaeté','Araçaí','Belo Horizonte','Belo Vale','Bom Despacho','Bonfim','Cachoeira da Prata',
                      'Caetanópolis','Capim Branco','Conceição do Pará','Contagem','Cordisburgo','Corinto',
                      'Dores do Indaiá','Felixlândia','Ibirité','Igaratinga','Inhaúma','Inimutaba','Itaúna',
                      'Itabirito','Itatiaiuçu','Leandro Ferreira','Mateus Leme','Matozinhos','Moeda',
                      'Morada Nova de Minas','Morro da Garça','Nova Lima','Onça de Pitangui','Paineiras',
                      'Pedro Leopoldo','Pitangui','Presidente Juscelino','Quartel Geral','Ribeirão das Neves',
                      'Rio Manso','Santana de Pirapama','Santo Hipólito','Sete Lagoas']


cidades_prox_limitrofes = ['Araújos','Augusto de Lima','Baldim','Biquinhas','Carmo do Cajuru','Cedro do Abaeté',
                           'Conceição do Mato Dentro','Confins','Congonhas','Congonhas do Norte','Crucilândia',
                           'Estrela do Indaiá','Funilândia','Gouveia','Itaguara','Jaboticatubas','Jeceaba',
                           'Jequitibá','Lagoa Santa','Lassance','Luz','Moema','Monjolos','Nova Serrana',
                           'Ouro Preto','Piedade dos Gerais','Prudente de Morais',
                           'Raposos','Rio Acima','Sabará','São Gonçalo do Abaeté','São Gonçalo do Pará',
                           'São Gotardo','São José da Lapa','Santa Bárbara','Santa Luzia','Santana do Riacho',
                           'Santo Antônio do Monte','Serra da Saudade','Tiros','Vespasiano']


#gera uma lista com o ID de todas as cidades a serem avaliadas
todas = cidades_selecionadas + cidades_limitrofes + cidades_prox_limitrofes

cidades = df[df['Nome Município'].isin(todas)]['Código'].unique()

In [4]:
cidades

array([310020, 310320, 310390, 310480, 310500, 310620, 310640, 310670,
       310700, 310740, 310810, 310900, 310960, 310990, 311250, 311420,
       311560, 311750, 311760, 311787, 311800, 311810, 311860, 311890,
       311910, 312060, 312090, 312320, 312410, 312470, 312570, 312600,
       312640, 312720, 312760, 312980, 313010, 313020, 313100, 313110,
       313190, 313220, 313370, 313380, 313460, 313540, 313570, 313665,
       313760, 313810, 313830, 313880, 313970, 314015, 314050, 314070,
       314110, 314230, 314240, 314250, 314350, 314360, 314480, 314520,
       314580, 314610, 314640, 314690, 314710, 314740, 314930, 314960,
       315040, 315140, 315200, 315320, 315360, 315370, 315390, 315460,
       315480, 315530, 315670, 315720, 315780, 315850, 315900, 316040,
       316060, 316170, 316180, 316210, 316292, 316295, 316310, 316553,
       316660, 316720, 316890, 317120], dtype=int64)

In [5]:
df = df[df['Código'].isin(cidades)]
df

,Município,Código,Nome Município,Casos Total,Hepatite A,Hepatite B,Hepatite C,Hepatite D,Hepatite A Total,Hepatite A 1999-2007,...,Tx Det F Hep B F 2011,Tx Det F Hep B F 2012,Tx Det F Hep B F 2013,Tx Det F Hep B F 2014,Tx Det F Hep B F 2015,Tx Det F Hep B F 2016,Tx Det F Hep B F 2017,Tx Det F Hep B F 2018,Tx Det F Hep B F 2019,Tx Det F Hep B F 2020
1,310020 Abaeté,310020,Abaeté,13,2,4,7,0,2,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
34,310320 Araçaí,310320,Araçaí,7,2,4,1,0,2,2,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
42,310390 Araújos,310390,Araújos,23,18,5,0,0,18,18,...,"0,0","0,0","0,0","0,0","23,2","0,0","0,0","0,0","0,0","0,0"
52,310480 Augusto de Lima,310480,Augusto de Lima,5,2,1,2,0,2,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
54,310500 Baldim,310500,Baldim,2,1,1,0,0,1,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,316553 Sarzedo,316553,Sarzedo,50,3,25,22,0,3,0,...,"15,1","0,0","0,0","20,5","0,0","0,0","0,0","0,0","12,2","11,9"
782,316660 Serra da Saudade,316660,Serra da Saudade,0,0,0,0,0,0,0,...,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
789,316720 Sete Lagoas,316720,Sete Lagoas,198,58,57,83,0,58,32,...,"2,7","1,8","0,9","0,9","0,8","0,8","0,0","0,8","0,8","0,0"
807,316890 Tiros,316890,Tiros,17,12,4,0,1,12,11,...,"0,0","30,1","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
842,317120 Vespasiano,317120,Vespasiano,221,27,116,75,3,27,13,...,"1,8","5,4","6,9","1,7","6,6","8,0","4,7","3,1","6,1","1,5"

In [6]:
df2 = df2[df2['Código'].isin(cidades)]
df2

,Município,Código,Nome Município,Hep C Novo Total,Hep C Novo 1999-2007,Hep C Novo 2008,Hep C Novo 2009,Hep C Novo 2010,Hep C Novo 2011,Hep C Novo 2012,...,Óbitos D 2010,Óbitos D 2011,Óbitos D 2012,Óbitos D 2013,Óbitos D 2014,Óbitos D 2015,Óbitos D 2016,Óbitos D 2017,Óbitos D 2018,Óbitos D 2019
1,310020 Abaeté,310020,Abaeté,8,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,310320 Araçaí,310320,Araçaí,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,310390 Araújos,310390,Araújos,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,310480 Augusto de Lima,310480,Augusto de Lima,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,310500 Baldim,310500,Baldim,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,316553 Sarzedo,316553,Sarzedo,31,3,2,2,1,2,4,...,0,0,0,0,0,0,0,0,0,0
782,316660 Serra da Saudade,316660,Serra da Saudade,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
789,316720 Sete Lagoas,316720,Sete Lagoas,145,42,11,12,9,9,3,...,0,0,0,0,0,0,0,0,0,0
807,316890 Tiros,316890,Tiros,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
842,317120 Vespasiano,317120,Vespasiano,93,12,4,4,1,7,7,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df = df.merge(df2)

In [8]:
df.columns

Index(['Município', 'Código', 'Nome Município', 'Casos Total', 'Hepatite A',
       'Hepatite B ', 'Hepatite C', 'Hepatite D', 'Hepatite A Total',
       'Hepatite A 1999-2007',
       ...
       'Óbitos D 2010', 'Óbitos D 2011', 'Óbitos D 2012', 'Óbitos D 2013',
       'Óbitos D 2014', 'Óbitos D 2015', 'Óbitos D 2016', 'Óbitos D 2017',
       'Óbitos D 2018', 'Óbitos D 2019'],
      dtype='object', length=417)

In [9]:
df = df.drop(['Casos Total', 'Hepatite A',
       'Hepatite B ', 'Hepatite C', 'Hepatite D', 'Hepatite A Total',
       'Hepatite A 1999-2007', 'Hep A M Total',  'Hep A M 1999-2007', 'Hep A F Total', 'Hep A F 1999-2007', 
        'Hepatite B Total', 'Hepatite B 1999-2007', 'Hep B M Total', 'Hep B M 1999-2007', 'Hep B F Total', 
        'Hep B F 1999-2007', 'Hep C Novo Total', 'Hep C Novo 1999-2007', 'Hep C Antigo Total', 'Hep C Antigo 1999-2007', 
        'Hepatite C Total', 'Hepatite C 1999-2007', 'Hep C M Total', 'Hep C M 1999-2007', 'Hep C F Total', 
        'Hep C F 1999-2007', 'Hepatite D Total', 'Hepatite D 1999-2007', 'Hep D M Total', 'Hep D M 1999-2007', 
        'Hep D F Total', 'Hep D F 1999-2007', 'Óbitos A Total', 'Óbitos A 2000-2007', 'Óbitos B Total', 
        'Óbitos B 2000-2007', 'Óbitos C Total', 'Óbitos C 2000-2007', 'Óbitos D Total', 'Óbitos D 2000-2007'], axis=1)

In [10]:
df_melt = df.melt(id_vars=['Município', 'Código', 'Nome Município'])

In [11]:
df_melt["variable"].unique()

array(['Hepatite A 2008', 'Hepatite A 2009', 'Hepatite A 2010',
       'Hepatite A 2011', 'Hepatite A 2012', 'Hepatite A 2013',
       'Hepatite A 2014', 'Hepatite A 2015', 'Hepatite A 2016',
       'Hepatite A 2017', 'Hepatite A 2018', 'Hepatite A 2019',
       'Hepatite A 2020', 'Tx Det Hep A 2008', 'Tx Det Hep A 2009',
       'Tx Det Hep A 2010', 'Tx Det Hep A 2011', 'Tx Det Hep A 2012',
       'Tx Det Hep A 2013', 'Tx Det Hep A 2014', 'Tx Det Hep A 2015',
       'Tx Det Hep A 2016', 'Tx Det Hep A 2017', 'Tx Det Hep A 2018',
       'Tx Det Hep A 2019', 'Tx Det Hep A 2020', 'Hep A M 2008',
       'Hep A M 2009', 'Hep A M 2010', 'Hep A M 2011', 'Hep A M 2012',
       'Hep A M 2013', 'Hep A M 2014', 'Hep A M 2015', 'Hep A M 2016',
       'Hep A M 2017', 'Hep A M 2018', 'Hep A M 2019', 'Hep A M 2020',
       'Tx Det M Hep A M 2008', 'Tx Det M Hep A M 2009',
       'Tx Det M Hep A M 2010', 'Tx Det M Hep A M 2011',
       'Tx Det M Hep A M 2012', 'Tx Det M Hep A M 2013',
       'Tx Det M Hep A M 2014', 'Tx Det M Hep A M 2015',
       'Tx Det M Hep A M 2016', 'Tx Det M Hep A M 2017',
       'Tx Det M Hep A M 2018', 'Tx Det M Hep A M 2019',
       'Tx Det M Hep A M 2020', 'Hep A F 2008', 'Hep A F 2009',
       'Hep A F 2010', 'Hep A F 2011', 'Hep A F 2012', 'Hep A F 2013',
       'Hep A F 2014', 'Hep A F 2015', 'Hep A F 2016', 'Hep A F 2017',
       'Hep A F 2018', 'Hep A F 2019', 'Hep A F 2020',
       'Tx Det F Hep A F 2008', 'Tx Det F Hep A F 2009',
       'Tx Det F Hep A F 2010', 'Tx Det F Hep A F 2011',
       'Tx Det F Hep A F 2012', 'Tx Det F Hep A F 2013',
       'Tx Det F Hep A F 2014', 'Tx Det F Hep A F 2015',
       'Tx Det F Hep A F 2016', 'Tx Det F Hep A F 2017',
       'Tx Det F Hep A F 2018', 'Tx Det F Hep A F 2019',
       'Tx Det F Hep A F 2020', 'Hepatite B 2008', 'Hepatite B 2009',
       'Hepatite B 2010', 'Hepatite B 2011', 'Hepatite B 2012',
       'Hepatite B 2013', 'Hepatite B 2014', 'Hepatite B 2015',
       'Hepatite B 2016', 'Hepatite B 2017', 'Hepatite B 2018',
       'Hepatite B 2019', 'Hepatite B 2020', 'Tx Det Hep B 2008',
       'Tx Det Hep B 2009', 'Tx Det Hep B 2010', 'Tx Det Hep B 2011',
       'Tx Det Hep B 2012', 'Tx Det Hep B 2013', 'Tx Det Hep B 2014',
       'Tx Det Hep B 2015', 'Tx Det Hep B 2016', 'Tx Det Hep B 2017',
       'Tx Det Hep B 2018', 'Tx Det Hep B 2019', 'Tx Det Hep B 2020',
       'Hep B M 2008', 'Hep B M 2009', 'Hep B M 2010', 'Hep B M 2011',
       'Hep B M 2012', 'Hep B M 2013', 'Hep B M 2014', 'Hep B M 2015',
       'Hep B M 2016', 'Hep B M 2017', 'Hep B M 2018', 'Hep B M 2019',
       'Hep B M 2020', 'Tx Det M Hep B M 2008', 'Tx Det M Hep B M 2009',
       'Tx Det M Hep B M 2010', 'Tx Det M Hep B M 2011',
       'Tx Det M Hep B M 2012', 'Tx Det M Hep B M 2013',
       'Tx Det M Hep B M 2014', 'Tx Det M Hep B M 2015',
       'Tx Det M Hep B M 2016', 'Tx Det M Hep B M 2017',
       'Tx Det M Hep B M 2018', 'Tx Det M Hep B M 2019',
       'Tx Det M Hep B M 2020', 'Hep B F 2008', 'Hep B F 2009',
       'Hep B F 2010', 'Hep B F 2011', 'Hep B F 2012', 'Hep B F 2013',
       'Hep B F 2014', 'Hep B F 2015', 'Hep B F 2016', 'Hep B F 2017',
       'Hep B F 2018', 'Hep B F 2019', 'Hep B F 2020',
       'Tx Det F Hep B F 2008', 'Tx Det F Hep B F 2009',
       'Tx Det F Hep B F 2010', 'Tx Det F Hep B F 2011',
       'Tx Det F Hep B F 2012', 'Tx Det F Hep B F 2013',
       'Tx Det F Hep B F 2014', 'Tx Det F Hep B F 2015',
       'Tx Det F Hep B F 2016', 'Tx Det F Hep B F 2017',
       'Tx Det F Hep B F 2018', 'Tx Det F Hep B F 2019',
       'Tx Det F Hep B F 2020', 'Hep C Novo 2008', 'Hep C Novo 2009',
       'Hep C Novo 2010', 'Hep C Novo 2011', 'Hep C Novo 2012',
       'Hep C Novo 2013', 'Hep C Novo 2014', 'Hep C Novo 2015',
       'Hep C Novo 2016', 'Hep C Novo 2017', 'Hep C Novo 2018',
       'Hep C Novo 2019', 'Hep C Novo 2020', 'Tx Det Hep C Novo 2008',
       'Tx Det Hep C Novo 2009', 'Tx Det Hep C Novo 2010',
       'Tx Det Hep C Novo 2011', 'Tx Det Hep C Novo 2012',
       'Tx Det Hep C Novo 2013', 'Tx Det Hep C Novo 2014',
       'Tx Det Hep C Novo 2015', 'Tx Det Hep C Novo 2016',
       'Tx Det Hep C Novo 2017', 'Tx Det Hep C Novo 2018',
       'Tx Det Hep C Novo 2019', 'Tx Det Hep C Novo 2020',
       'Hep C Antigo 2008', 'Hep C Antigo 2009', 'Hep C Antigo 2010',
       'Hep C Antigo 2011', 'Hep C Antigo 2012', 'Hep C Antigo 2013',
       'Hep C Antigo 2014', 'Hep C Antigo 2015', 'Hep C Antigo 2016',
       'Hep C Antigo 2017', 'Hep C Antigo 2018', 'Hep C Antigo 2019',
       'Hep C Antigo 2020', 'Tx Det Hep C Antigo 2008',
       'Tx Det Hep C Antigo 2009', 'Tx Det Hep C Antigo 2010',
       'Tx Det Hep C Antigo 2011', 'Tx Det Hep C Antigo 2012',
       'Tx Det Hep C Antigo 2013', 'Tx Det Hep C Antigo 2014',
       'Tx Det Hep C Antigo 2015', 'Tx Det Hep C Antigo 2016',
       'Tx Det Hep C Antigo 2017', 'Tx Det Hep C Antigo 2018',
       'Tx Det Hep C Antigo 2019', 'Tx Det Hep C Antigo 2020',
       'Hepatite C 2008', 'Hepatite C 2009', 'Hepatite C 2010',
       'Hepatite C 2011', 'Hepatite C 2012', 'Hepatite C 2013',
       'Hepatite C 2014', 'Hepatite C 2015', 'Hepatite C 2016',
       'Hepatite C 2017', 'Hepatite C 2018', 'Hepatite C 2019',
       'Hepatite C 2020', 'Tx Det Hep C 2008', 'Tx Det Hep C 2009',
       'Tx Det Hep C 2010', 'Tx Det Hep C 2011', 'Tx Det Hep C 2012',
       'Tx Det Hep C 2013', 'Tx Det Hep C 2014', 'Tx Det Hep C 2015',
       'Tx Det Hep C 2016', 'Tx Det Hep C 2017', 'Tx Det Hep C 2018',
       'Tx Det Hep C 2019', 'Tx Det Hep C 2020', 'Hep C M 2008',
       'Hep C M 2009', 'Hep C M 2010', 'Hep C M 2011', 'Hep C M 2012',
       'Hep C M 2013', 'Hep C M 2014', 'Hep C M 2015', 'Hep C M 2016',
       'Hep C M 2017', 'Hep C M 2018', 'Hep C M 2019', 'Hep C M 2020',
       'Tx Det M Hep C M 2008', 'Tx Det M Hep C M 2009',
       'Tx Det M Hep C M 2010', 'Tx Det M Hep C M 2011',
       'Tx Det M Hep C M 2012', 'Tx Det M Hep C M 2013',
       'Tx Det M Hep C M 2014', 'Tx Det M Hep C M 2015',
       'Tx Det M Hep C M 2016', 'Tx Det M Hep C M 2017',
       'Tx Det M Hep C M 2018', 'Tx Det M Hep C M 2019',
       'Tx Det M Hep C M 2020', 'Hep C F 2008', 'Hep C F 2009',
       'Hep C F 2010', 'Hep C F 2011', 'Hep C F 2012', 'Hep C F 2013',
       'Hep C F 2014', 'Hep C F 2015', 'Hep C F 2016', 'Hep C F 2017',
       'Hep C F 2018', 'Hep C F 2019', 'Hep C F 2020',
       'Tx Det F Hep C F 2008', 'Tx Det F Hep C F 2009',
       'Tx Det F Hep C F 2010', 'Tx Det F Hep C F 2011',
       'Tx Det F Hep C F 2012', 'Tx Det F Hep C F 2013',
       'Tx Det F Hep C F 2014', 'Tx Det F Hep C F 2015',
       'Tx Det F Hep C F 2016', 'Tx Det F Hep C F 2017',
       'Tx Det F Hep C F 2018', 'Tx Det F Hep C F 2019',
       'Tx Det F Hep C F 2020', 'Hepatite D 2008', 'Hepatite D 2009',
       'Hepatite D 2010', 'Hepatite D 2011', 'Hepatite D 2012',
       'Hepatite D 2013', 'Hepatite D 2014', 'Hepatite D 2015',
       'Hepatite D 2016', 'Hepatite D 2017', 'Hepatite D 2018',
       'Hepatite D 2019', 'Hepatite D 2020', 'Hep D M 2008',
       'Hep D M 2009', 'Hep D M 2010', 'Hep D M 2011', 'Hep D M 2012',
       'Hep D M 2013', 'Hep D M 2014', 'Hep D M 2015', 'Hep D M 2016',
       'Hep D M 2017', 'Hep D M 2018', 'Hep D M 2019', 'Hep D M 2020',
       'Hep D F 2008', 'Hep D F 2009', 'Hep D F 2010', 'Hep D F 2011',
       'Hep D F 2012', 'Hep D F 2013', 'Hep D F 2014', 'Hep D F 2015',
       'Hep D F 2016', 'Hep D F 2017', 'Hep D F 2018', 'Hep D F 2019',
       'Hep D F 2020', 'Óbitos A 2008', 'Óbitos A 2009', 'Óbitos A 2010',
       'Óbitos A 2011', 'Óbitos A 2012', 'Óbitos A 2013', 'Óbitos A 2014',
       'Óbitos A 2015', 'Óbitos A 2016', 'Óbitos A 2017', 'Óbitos A 2018',
       'Óbitos A 2019', 'Óbitos B 2008', 'Óbitos B 2009', 'Óbitos B 2010',
       'Óbitos B 2011', 'Óbitos B 2012', 'Óbitos B 2013', 'Óbitos B 2014',
       'Óbitos B 2015', 'Óbitos B 2016', 'Óbitos B 2017', 'Óbitos B 2018',
       'Óbitos B 2019', 'Óbitos C 2008', 'Óbitos C 2009', 'Óbitos C 2010',
       'Óbitos C 2011', 'Óbitos C 2012', 'Óbitos C 2013', 'Óbitos C 2014',
       'Óbitos C 2015', 'Óbitos C 2016', 'Óbitos C 2017', 'Óbitos C 2018',
       'Óbitos C 2019', 'Óbitos D 2008', 'Óbitos D 2009', 'Óbitos D 2010',
       'Óbitos D 2011', 'Óbitos D 2012', 'Óbitos D 2013', 'Óbitos D 2014',
       'Óbitos D 2015', 'Óbitos D 2016', 'Óbitos D 2017', 'Óbitos D 2018',
       'Óbitos D 2019'], dtype=object)

In [12]:
anos = (df.melt(id_vars=['Município', 'Código', 'Nome Município']).variable.
        str.strip().
        str.slice(start=-4))

In [13]:
anos.unique()

array(['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020'], dtype=object)

In [14]:
df_melt["variable"] = df_melt.variable.str.slice(stop=-5)

In [15]:
df_melt["variable"].unique()

array(['Hepatite A', 'Tx Det Hep A', 'Hep A M', 'Tx Det M Hep A M',
       'Hep A F', 'Tx Det F Hep A F', 'Hepatite B', 'Tx Det Hep B',
       'Hep B M', 'Tx Det M Hep B M', 'Hep B F', 'Tx Det F Hep B F',
       'Hep C Novo', 'Tx Det Hep C Novo', 'Hep C Antigo',
       'Tx Det Hep C Antigo', 'Hepatite C', 'Tx Det Hep C', 'Hep C M',
       'Tx Det M Hep C M', 'Hep C F', 'Tx Det F Hep C F', 'Hepatite D',
       'Hep D M', 'Hep D F', 'Óbitos A', 'Óbitos B', 'Óbitos C',
       'Óbitos D'], dtype=object)

In [16]:
df_melt["ano"] = anos
df_melt

,Município,Código,Nome Município,variable,value,ano
0,310020 Abaeté,310020,Abaeté,Hepatite A,0,2008
1,310320 Araçaí,310320,Araçaí,Hepatite A,0,2008
2,310390 Araújos,310390,Araújos,Hepatite A,0,2008
3,310480 Augusto de Lima,310480,Augusto de Lima,Hepatite A,0,2008
4,310500 Baldim,310500,Baldim,Hepatite A,0,2008
...,...,...,...,...,...,...
37295,316553 Sarzedo,316553,Sarzedo,Óbitos D,0,2019
37296,316660 Serra da Saudade,316660,Serra da Saudade,Óbitos D,0,2019
37297,316720 Sete Lagoas,316720,Sete Lagoas,Óbitos D,0,2019
37298,316890 Tiros,316890,Tiros,Óbitos D,0,2019
37299,317120 Vespasiano,317120,Vespasiano,Óbitos D,0,2019

In [17]:
set(df_melt[df_melt.columns[1:]].variable)

{'Hep A F',
 'Hep A M',
 'Hep B F',
 'Hep B M',
 'Hep C Antigo',
 'Hep C F',
 'Hep C M',
 'Hep C Novo',
 'Hep D F',
 'Hep D M',
 'Hepatite A',
 'Hepatite B',
 'Hepatite C',
 'Hepatite D',
 'Tx Det F Hep A F',
 'Tx Det F Hep B F',
 'Tx Det F Hep C F',
 'Tx Det Hep A',
 'Tx Det Hep B',
 'Tx Det Hep C',
 'Tx Det Hep C Antigo',
 'Tx Det Hep C Novo',
 'Tx Det M Hep A M',
 'Tx Det M Hep B M',
 'Tx Det M Hep C M',
 'Óbitos A',
 'Óbitos B',
 'Óbitos C',
 'Óbitos D'}

In [18]:
df_melt.pivot(columns="variable").columns

MultiIndex([('Município',             'Hep A F'),
            ('Município',             'Hep A M'),
            ('Município',             'Hep B F'),
            ('Município',             'Hep B M'),
            ('Município',        'Hep C Antigo'),
            ('Município',             'Hep C F'),
            ('Município',             'Hep C M'),
            ('Município',          'Hep C Novo'),
            ('Município',             'Hep D F'),
            ('Município',             'Hep D M'),
            ...
            (      'ano',        'Tx Det Hep C'),
            (      'ano', 'Tx Det Hep C Antigo'),
            (      'ano',   'Tx Det Hep C Novo'),
            (      'ano',    'Tx Det M Hep A M'),
            (      'ano',    'Tx Det M Hep B M'),
            (      'ano',    'Tx Det M Hep C M'),
            (      'ano',            'Óbitos A'),
            (      'ano',            'Óbitos B'),
            (      'ano',            'Óbitos C'),
            (      'ano',            'Óbitos D')],
           names=[None, 'variable'], length=145)

In [19]:
df_melt

,Município,Código,Nome Município,variable,value,ano
0,310020 Abaeté,310020,Abaeté,Hepatite A,0,2008
1,310320 Araçaí,310320,Araçaí,Hepatite A,0,2008
2,310390 Araújos,310390,Araújos,Hepatite A,0,2008
3,310480 Augusto de Lima,310480,Augusto de Lima,Hepatite A,0,2008
4,310500 Baldim,310500,Baldim,Hepatite A,0,2008
...,...,...,...,...,...,...
37295,316553 Sarzedo,316553,Sarzedo,Óbitos D,0,2019
37296,316660 Serra da Saudade,316660,Serra da Saudade,Óbitos D,0,2019
37297,316720 Sete Lagoas,316720,Sete Lagoas,Óbitos D,0,2019
37298,316890 Tiros,316890,Tiros,Óbitos D,0,2019
37299,317120 Vespasiano,317120,Vespasiano,Óbitos D,0,2019

In [20]:
df_melt = df_melt.drop(["Município"], axis=1)
df_melt.columns = ['Código', 'Município', 'variavel', 'valor', 'ano']
df_melt

       Código         Município    variavel valor   ano
0      310020            Abaeté  Hepatite A     0  2008
1      310320            Araçaí  Hepatite A     0  2008
2      310390           Araújos  Hepatite A     0  2008
3      310480   Augusto de Lima  Hepatite A     0  2008
4      310500            Baldim  Hepatite A     0  2008
...       ...               ...         ...   ...   ...
37295  316553           Sarzedo    Óbitos D     0  2019
37296  316660  Serra da Saudade    Óbitos D     0  2019
37297  316720       Sete Lagoas    Óbitos D     0  2019
37298  316890             Tiros    Óbitos D     0  2019
37299  317120        Vespasiano    Óbitos D     0  2019

[37300 rows x 5 columns]

In [21]:
df_melt = df_melt.pivot(values='valor', index=['Código', 'Município', 'ano'], columns=['variavel'])
df_melt

variavel               Hep A F Hep A M Hep B F Hep B M Hep C Antigo Hep C F  \
Código Município  ano
310020 Abaeté     2008       0       0       0       0            0       0
                  2009       0       0       0       1            1       0
                  2010       1       0       0       2            0       0
                  2011       0       0       0       0            0       0
                  2012       0       0       0       0            0       0
...                        ...     ...     ...     ...          ...     ...
317120 Vespasiano 2016       1       0       5       3            1       5
                  2017       0       0       3       3            2       7
                  2018       0       0       2       3            2       3
                  2019       2       2       4       4            0       2
                  2020       0       0       1       1            0       1

variavel               Hep C M Hep C Novo Hep D F Hep D M  ... Tx Det Hep C  \
Código Município  ano                                      ...
310020 Abaeté     2008       0          0       0       0  ...          0,0
                  2009       1          1       0       0  ...          4,3
                  2010       0          0       0       0  ...          0,0
                  2011       0          0       0       0  ...          0,0
                  2012       0          0       0       0  ...          0,0
...                        ...        ...     ...     ...  ...          ...
317120 Vespasiano 2016       7         12       0       0  ...          9,9
                  2017       4         11       0       0  ...          8,9
                  2018       7         10       0       0  ...          8,0
                  2019       2          4       0       0  ...          3,1
                  2020       0          1       0       0  ...          0,8

variavel               Tx Det Hep C Antigo Tx Det Hep C Novo Tx Det M Hep A M  \
Código Município  ano
310020 Abaeté     2008                 0,0               0,0              0,0
                  2009                 4,3               4,3              0,0
                  2010                 0,0               0,0              0,0
                  2011                 0,0               0,0              0,0
                  2012                 0,0               0,0              0,0
...                                    ...               ...              ...
317120 Vespasiano 2016                 0,8               9,9              0,0
                  2017                 1,6               8,9              0,0
                  2018                 1,6               8,0              0,0
                  2019                 0,0               3,1              3,2
                  2020                 0,0               0,8              0,0

variavel               Tx Det M Hep B M Tx Det M Hep C M Óbitos A Óbitos B  \
Código Município  ano
310020 Abaeté     2008              0,0              0,0        0        0
                  2009              8,7              8,7        0        0
                  2010             17,8              0,0        0        0
                  2011              0,0              0,0        0        0
                  2012              0,0              0,0        0        0
...                                 ...              ...      ...      ...
317120 Vespasiano 2016              5,1             11,9        0        0
                  2017              5,0              6,7        0        0
                  2018              4,9             11,5        0        0
                  2019              6,5              3,2        0        0
                  2020              1,6              0,0      NaN      NaN

variavel               Óbitos C Óbitos D
Código Município  ano
310020 Abaeté     2008        0        0
                  2009        0        0
                  2010        0        0
                  2011        0        0
                  2012        0        0
...                         ...      ...
317120 Vespasiano 2016        0        0
                  2017        0        0
                  2018        0        0
                  2019        1        0
                  2020      NaN      NaN

[1300 rows x 29 columns]

In [22]:
df_melt = df_melt.reset_index()

In [24]:
df_melt.to_csv('hepatite.csv', index=False)